baseURL = "https://dennismagnusson.fi/"
languageCode = 'en-us'
theme = "hugo-kiera"
paginate = 5
title = "Dennis Magnusson"

pygmentsCodeFences = true

[author]
name = "Dennis Magnusson"               #Author name
github = "dennis-magnusson"             #Github username
linkedin = "dennis-magnusson-b17949231" #LinkedIn username

[params]
# tagline = "the tagline for this website"
customCSS = []             #Optional Customised CSS
disableDarkModeCSS = false # disables css style for users using dark-mode
menu = "main"
meta = "false"
